from shouter.shouter import Shouter


def main():
    my_api_token = "abcde123456789" # Generated by the Mobile APP
    my_shouter = Shouter(api_token=my_api_token)

    my_shouter.shout("Hello World")


if __name__ == "__main__":
    main()
